###
# Send request:
POST http://127.0.0.1:12345/jobs HTTP/1.1
content-type: application/json

{"contest_id":0,"language":"Rust","problem_id":0,"source_code":"fn main() { println!(\"Hello World!\"); loop {} }","user_id":0}
###
# Got response:
# HTTP 200
# content-length: 385
# vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
# content-type: application/json
# access-control-allow-credentials: true
# access-control-expose-headers: content-type
# date: Fri, 09 Sep 2022 02:24:20 GMT
# 
# {"cases":[{"id":0,"info":"","memory":0,"result":"Waiting","time":0},{"id":1,"info":"","memory":0,"result":"Waiting","time":0}],"created_time":"2022-09-09T02:24:21.043Z","id":0,"result":"Waiting","score":0.0,"state":"Queueing","submission":{"contest_id":0,"language":"Rust","problem_id":0,"source_code":"fn main() { println!(\"Hello World!\"); loop {} }","user_id":0},"updated_time":""}
###
# Send request:
POST http://127.0.0.1:12345/jobs HTTP/1.1
content-type: application/json

{"contest_id":0,"language":"Rust","problem_id":0,"source_code":"fn main() { println!(\"Hello World!\"); loop {} }","user_id":0}
###
# Got response:
# HTTP 200
# content-length: 385
# vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
# content-type: application/json
# access-control-allow-credentials: true
# access-control-expose-headers: content-type
# date: Fri, 09 Sep 2022 02:24:20 GMT
# 
# {"cases":[{"id":0,"info":"","memory":0,"result":"Waiting","time":0},{"id":1,"info":"","memory":0,"result":"Waiting","time":0}],"created_time":"2022-09-09T02:24:21.046Z","id":1,"result":"Waiting","score":0.0,"state":"Queueing","submission":{"contest_id":0,"language":"Rust","problem_id":0,"source_code":"fn main() { println!(\"Hello World!\"); loop {} }","user_id":0},"updated_time":""}
###
# Send request:
POST http://127.0.0.1:12345/jobs HTTP/1.1
content-type: application/json

{"contest_id":0,"language":"Rust","problem_id":0,"source_code":"fn main() { println!(\"Hello World!\"); loop {} }","user_id":0}
###
# Got response:
# HTTP 200
# content-length: 385
# vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
# content-type: application/json
# access-control-allow-credentials: true
# access-control-expose-headers: content-type
# date: Fri, 09 Sep 2022 02:24:20 GMT
# 
# {"cases":[{"id":0,"info":"","memory":0,"result":"Waiting","time":0},{"id":1,"info":"","memory":0,"result":"Waiting","time":0}],"created_time":"2022-09-09T02:24:21.051Z","id":2,"result":"Waiting","score":0.0,"state":"Queueing","submission":{"contest_id":0,"language":"Rust","problem_id":0,"source_code":"fn main() { println!(\"Hello World!\"); loop {} }","user_id":0},"updated_time":""}
###
# Send request:
GET http://127.0.0.1:12345/jobs/0 HTTP/1.1


###
# Got response:
# HTTP 200
# content-length: 384
# vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
# content-type: application/json
# access-control-allow-credentials: true
# access-control-expose-headers: content-type
# date: Fri, 09 Sep 2022 02:24:20 GMT
# 
# {"cases":[{"id":0,"info":"","memory":0,"result":"Running","time":0},{"id":1,"info":"","memory":0,"result":"Waiting","time":0}],"created_time":"2022-09-09T02:24:21.043Z","id":0,"result":"Running","score":0.0,"state":"Running","submission":{"contest_id":0,"language":"Rust","problem_id":0,"source_code":"fn main() { println!(\"Hello World!\"); loop {} }","user_id":0},"updated_time":""}
###
# Send request:
GET http://127.0.0.1:12345/jobs/0 HTTP/1.1


###
# Got response:
# HTTP 200
# content-length: 401
# vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
# content-type: application/json
# access-control-allow-credentials: true
# access-control-expose-headers: content-type
# date: Fri, 09 Sep 2022 02:24:22 GMT
# 
# {"cases":[{"id":0,"info":"","memory":0,"result":"Compilation Success","time":147464},{"id":1,"info":"","memory":0,"result":"Running","time":0}],"created_time":"2022-09-09T02:24:21.043Z","id":0,"result":"Running","score":0.0,"state":"Running","submission":{"contest_id":0,"language":"Rust","problem_id":0,"source_code":"fn main() { println!(\"Hello World!\"); loop {} }","user_id":0},"updated_time":""}
###
# Send request:
GET http://127.0.0.1:12345/jobs/0 HTTP/1.1


###
# Got response:
# HTTP 200
# content-length: 401
# vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
# content-type: application/json
# access-control-allow-credentials: true
# access-control-expose-headers: content-type
# date: Fri, 09 Sep 2022 02:24:23 GMT
# 
# {"cases":[{"id":0,"info":"","memory":0,"result":"Compilation Success","time":147464},{"id":1,"info":"","memory":0,"result":"Running","time":0}],"created_time":"2022-09-09T02:24:21.043Z","id":0,"result":"Running","score":0.0,"state":"Running","submission":{"contest_id":0,"language":"Rust","problem_id":0,"source_code":"fn main() { println!(\"Hello World!\"); loop {} }","user_id":0},"updated_time":""}
###
# Send request:
GET http://127.0.0.1:12345/jobs/0 HTTP/1.1


###
# Got response:
# HTTP 200
# content-length: 401
# vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
# content-type: application/json
# access-control-allow-credentials: true
# access-control-expose-headers: content-type
# date: Fri, 09 Sep 2022 02:24:24 GMT
# 
# {"cases":[{"id":0,"info":"","memory":0,"result":"Compilation Success","time":147464},{"id":1,"info":"","memory":0,"result":"Running","time":0}],"created_time":"2022-09-09T02:24:21.043Z","id":0,"result":"Running","score":0.0,"state":"Running","submission":{"contest_id":0,"language":"Rust","problem_id":0,"source_code":"fn main() { println!(\"Hello World!\"); loop {} }","user_id":0},"updated_time":""}
###
# Send request:
GET http://127.0.0.1:12345/jobs/0 HTTP/1.1


###
# Got response:
# HTTP 200
# content-length: 401
# vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
# content-type: application/json
# access-control-allow-credentials: true
# access-control-expose-headers: content-type
# date: Fri, 09 Sep 2022 02:24:25 GMT
# 
# {"cases":[{"id":0,"info":"","memory":0,"result":"Compilation Success","time":147464},{"id":1,"info":"","memory":0,"result":"Running","time":0}],"created_time":"2022-09-09T02:24:21.043Z","id":0,"result":"Running","score":0.0,"state":"Running","submission":{"contest_id":0,"language":"Rust","problem_id":0,"source_code":"fn main() { println!(\"Hello World!\"); loop {} }","user_id":0},"updated_time":""}
###
# Send request:
GET http://127.0.0.1:12345/jobs/0 HTTP/1.1


###
# Got response:
# HTTP 200
# content-length: 401
# vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
# content-type: application/json
# access-control-allow-credentials: true
# access-control-expose-headers: content-type
# date: Fri, 09 Sep 2022 02:24:26 GMT
# 
# {"cases":[{"id":0,"info":"","memory":0,"result":"Compilation Success","time":147464},{"id":1,"info":"","memory":0,"result":"Running","time":0}],"created_time":"2022-09-09T02:24:21.043Z","id":0,"result":"Running","score":0.0,"state":"Running","submission":{"contest_id":0,"language":"Rust","problem_id":0,"source_code":"fn main() { println!(\"Hello World!\"); loop {} }","user_id":0},"updated_time":""}
###
# Send request:
GET http://127.0.0.1:12345/jobs/0 HTTP/1.1


###
# Got response:
# HTTP 200
# content-length: 401
# vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
# content-type: application/json
# access-control-allow-credentials: true
# access-control-expose-headers: content-type
# date: Fri, 09 Sep 2022 02:24:27 GMT
# 
# {"cases":[{"id":0,"info":"","memory":0,"result":"Compilation Success","time":147464},{"id":1,"info":"","memory":0,"result":"Running","time":0}],"created_time":"2022-09-09T02:24:21.043Z","id":0,"result":"Running","score":0.0,"state":"Running","submission":{"contest_id":0,"language":"Rust","problem_id":0,"source_code":"fn main() { println!(\"Hello World!\"); loop {} }","user_id":0},"updated_time":""}
###
# Send request:
GET http://127.0.0.1:12345/jobs/0 HTTP/1.1


###
# Got response:
# HTTP 200
# content-length: 401
# vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
# content-type: application/json
# access-control-allow-credentials: true
# access-control-expose-headers: content-type
# date: Fri, 09 Sep 2022 02:24:28 GMT
# 
# {"cases":[{"id":0,"info":"","memory":0,"result":"Compilation Success","time":147464},{"id":1,"info":"","memory":0,"result":"Running","time":0}],"created_time":"2022-09-09T02:24:21.043Z","id":0,"result":"Running","score":0.0,"state":"Running","submission":{"contest_id":0,"language":"Rust","problem_id":0,"source_code":"fn main() { println!(\"Hello World!\"); loop {} }","user_id":0},"updated_time":""}
###
# Send request:
GET http://127.0.0.1:12345/jobs/0 HTTP/1.1


###
# Got response:
# HTTP 200
# content-length: 401
# vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
# content-type: application/json
# access-control-allow-credentials: true
# access-control-expose-headers: content-type
# date: Fri, 09 Sep 2022 02:24:29 GMT
# 
# {"cases":[{"id":0,"info":"","memory":0,"result":"Compilation Success","time":147464},{"id":1,"info":"","memory":0,"result":"Running","time":0}],"created_time":"2022-09-09T02:24:21.043Z","id":0,"result":"Running","score":0.0,"state":"Running","submission":{"contest_id":0,"language":"Rust","problem_id":0,"source_code":"fn main() { println!(\"Hello World!\"); loop {} }","user_id":0},"updated_time":""}
###
# Send request:
GET http://127.0.0.1:12345/jobs/0 HTTP/1.1


###
# Got response:
# HTTP 200
# content-length: 401
# vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
# content-type: application/json
# access-control-allow-credentials: true
# access-control-expose-headers: content-type
# date: Fri, 09 Sep 2022 02:24:30 GMT
# 
# {"cases":[{"id":0,"info":"","memory":0,"result":"Compilation Success","time":147464},{"id":1,"info":"","memory":0,"result":"Running","time":0}],"created_time":"2022-09-09T02:24:21.043Z","id":0,"result":"Running","score":0.0,"state":"Running","submission":{"contest_id":0,"language":"Rust","problem_id":0,"source_code":"fn main() { println!(\"Hello World!\"); loop {} }","user_id":0},"updated_time":""}
###
# Send request:
GET http://127.0.0.1:12345/jobs/0 HTTP/1.1


###
# Got response:
# HTTP 200
# content-length: 401
# vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
# content-type: application/json
# access-control-allow-credentials: true
# access-control-expose-headers: content-type
# date: Fri, 09 Sep 2022 02:24:31 GMT
# 
# {"cases":[{"id":0,"info":"","memory":0,"result":"Compilation Success","time":147464},{"id":1,"info":"","memory":0,"result":"Running","time":0}],"created_time":"2022-09-09T02:24:21.043Z","id":0,"result":"Running","score":0.0,"state":"Running","submission":{"contest_id":0,"language":"Rust","problem_id":0,"source_code":"fn main() { println!(\"Hello World!\"); loop {} }","user_id":0},"updated_time":""}
###
# Send request:
GET http://127.0.0.1:12345/jobs/0 HTTP/1.1


###
# Got response:
# HTTP 200
# content-length: 457
# vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
# content-type: application/json
# access-control-allow-credentials: true
# access-control-expose-headers: content-type
# date: Fri, 09 Sep 2022 02:24:32 GMT
# 
# {"cases":[{"id":0,"info":"","memory":0,"result":"Compilation Success","time":147464},{"id":1,"info":"","memory":0,"result":"Time Limit Exceeded","time":10100444}],"created_time":"2022-09-09T02:24:21.043Z","id":0,"result":"Time Limit Exceeded","score":0.0,"state":"Finished","submission":{"contest_id":0,"language":"Rust","problem_id":0,"source_code":"fn main() { println!(\"Hello World!\"); loop {} }","user_id":0},"updated_time":"2022-09-09T02:24:31.294Z"}
###
# Send request:
GET http://127.0.0.1:12345/jobs/1 HTTP/1.1


###
# Got response:
# HTTP 200
# content-length: 457
# vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
# content-type: application/json
# access-control-allow-credentials: true
# access-control-expose-headers: content-type
# date: Fri, 09 Sep 2022 02:24:32 GMT
# 
# {"cases":[{"id":0,"info":"","memory":0,"result":"Compilation Success","time":135717},{"id":1,"info":"","memory":0,"result":"Time Limit Exceeded","time":10101129}],"created_time":"2022-09-09T02:24:21.046Z","id":1,"result":"Time Limit Exceeded","score":0.0,"state":"Finished","submission":{"contest_id":0,"language":"Rust","problem_id":0,"source_code":"fn main() { println!(\"Hello World!\"); loop {} }","user_id":0},"updated_time":"2022-09-09T02:24:31.288Z"}
###
# Send request:
GET http://127.0.0.1:12345/jobs/2 HTTP/1.1


###
# Got response:
# HTTP 200
# content-length: 457
# vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
# content-type: application/json
# access-control-allow-credentials: true
# access-control-expose-headers: content-type
# date: Fri, 09 Sep 2022 02:24:32 GMT
# 
# {"cases":[{"id":0,"info":"","memory":0,"result":"Compilation Success","time":149049},{"id":1,"info":"","memory":0,"result":"Time Limit Exceeded","time":10101267}],"created_time":"2022-09-09T02:24:21.051Z","id":2,"result":"Time Limit Exceeded","score":0.0,"state":"Finished","submission":{"contest_id":0,"language":"Rust","problem_id":0,"source_code":"fn main() { println!(\"Hello World!\"); loop {} }","user_id":0},"updated_time":"2022-09-09T02:24:31.312Z"}
